export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_USERS = 'GET_USERS';
export const USER_ANSWER_QUESTION = 'USER_ANSWER_QUESTION';
export const USER_ADD_NEW_QUESTION = 'USER_ADD_NEW_QUESTION';

export const GET_QUESTIONS = 'GET_QUESTIONS';
export const ADD_NEW_QUESTION = 'ADD_NEW_QUESTION';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
